version: '2'
services:
  picopik-cli:
    build: 
        context: .
        dockerfile: cli-dockerfile
    volumes:
      - "../picopik-cli:/picopik/picopik-server/picopik-cli"
      - "../picopik-models:/picopik/picopik-server/picopik-models"
      - "../.env:/picopik/picopik-server/.env"
    working_dir: "/."
    command: tail -F anything
    
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - ../.env      
    ports:
      - "3306:3306"
    volumes:
      - picopik:/var/lib/mysql

volumes:
  picopik: