version: '2'
services:
  picopik-server:
    build: .
    volumes:
      - "../:/picopik"
    command: "systemfd --no-pid -s 0.0.0.0:8080 -- cargo watch -x run"
    working_dir: "/picopik"
    ports:
      - "8080:8080"

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - ../.env      
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
      
