CREATE TABLE users(
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(25) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password TEXT NOT NULL,
    bio VARCHAR(500),
    image TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_online TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
